### ISSUE TITLE
replace cross-env to native node.js env

### ISSUE THREAD

**Issue by casaub0n** [casaub0n/casaub0n#1365]
```console
> cross-env CHROME='C:\Program Files\Google\Chrome\Application\chrome.exe' node --no-warnings --import tsx src/test.ts

指定されたパスが見つかりません。
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: spawn Files\Google\Chrome\Application\chrome.exe ENOENT
    at notFoundError (C:\Users\netza\sandbox\casaub0n\node_modules\.pnpm\cross-spawn@7.0.3\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\netza\sandbox\casaub0n\node_modules\.pnpm\cross-spawn@7.0.3\node_modules\cross-spawn\lib\enoent.js:40:16)
    at cp.emit (C:\Users\netza\sandbox\casaub0n\node_modules\.pnpm\cross-spawn@7.0.3\node_modules\cross-spawn\lib\enoent.js:27:25)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
Emitted 'error' event on ChildProcess instance at:
    at cp.emit (C:\Users\netza\sandbox\casaub0n\node_modules\.pnpm\cross-spawn@7.0.3\node_modules\cross-spawn\lib\enoent.js:30:37)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn Files\\Google\\Chrome\\Application\\chrome.exe',
  path: 'Files\\Google\\Chrome\\Application\\chrome.exe',
  spawnargs: [ 'node', '--no-warnings', '--import', 'tsx', 'src/test.ts' ]
}

Node.js v20.12.2
 ELIFECYCLE  Test failed. See above for more details.
```

**Comment by casaub0n** [comment]
https://www.wisdomgeek.com/development/web-development/javascript/node-js-20-6-adds-built-in-support-for-env-files/
