### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by casaub0n** [casaub0n/casaub0n#444]
```console
  ● src/components/organisms/QuestionForm/QuestionForm.test.tsx › show error message when submit the empty value

    expect(element).toHaveErrorMessage()

    Expected the element to have invalid state indicated by:
      aria-invalid="true"
    Received:
      aria-invalid="false"

    Ignored nodes: comments, script, style
    <html>
      <head />
      <body>
        <div>
          <form
            class="c-ciDJDx"
          >
            <div
              class="c-kpxNBX"
              data-invalid="true"
            >
              <div
                class="c-dhzjXW c-dhzjXW-ieHkOTx-css"
              >
                <label
                  class="c-dNkczQ"
                  data-invalid="true"
                  for="radix-:r4:"
                >
                  Email
                </label>
              </div>
              <input
                aria-errormessage=":r3:"
                aria-invalid="false"
                aria-label="email"
                class="c-iVEVNR"
                data-invalid="true"
                id="radix-:r4:"
                name="email"
                required=""
                title=""
                type="email"
                value=""
              />
            </div>
            <div
              class="c-kpxNBX"
              data-invalid="true"
            >
              <div
                class="c-dhzjXW c-dhzjXW-ieHkOTx-css"
              >
                <label
                  class="c-dNkczQ"
                  data-invalid="true"
                  for="radix-:r5:"
                >
                  Question
                </label>
              </div>
              <textarea
                aria-invalid="false"
                aria-label="question"
                class="c-jKqBUa"
                data-invalid="true"
                id="radix-:r5:"
                name="question"
                required=""
                title=""
              />
            </div>
            <button
              class="c-ezaLUS c-ezaLUS-ifARuGn-css"
              type="submit"
            >
              Post question
            </button>
          </form>
        </div>
      </body>
    </html>

      15 |     await EmptyName.play({ canvasElement: container });
      16 |     await waitFor(() => {
    > 17 |       expect(getByRole("textbox", { name: "email" })).toHaveErrorMessage("Please enter your email");
         |                                                       ^
      18 |     });
      19 |   });
      20 |   test.todo("show error message when submit the empty value");

      at toHaveErrorMessage (src/components/organisms/QuestionForm/QuestionForm.test.tsx:17:55)
      at runWithExpensiveErrorDiagnosticsDisabled (../../node_modules/.pnpm/@testing-library+dom@9.3.1/node_modules/@testing-library/dom/dist/config.js:47:12)
      at checkCallback (../../node_modules/.pnpm/@testing-library+dom@9.3.1/node_modules/@testing-library/dom/dist/wait-for.js:121:77)
      at checkRealTimersCallback (../../node_modules/.pnpm/@testing-library+dom@9.3.1/node_modules/@testing-library/dom/dist/wait-for.js:115:16)
      at Timeout.task [as _onTimeout] (../../node_modules/.pnpm/jsdom@20.0.3/node_modules/jsdom/lib/jsdom/browser/Window.js:520:19)
```
![スクリーンショット 2023-07-02 211236](https://github.com/casaub0n/casaub0n/assets/6220791/ee469655-a4fb-4fc0-958e-72bf4deed319)
![report2](https://github.com/casaub0n/casaub0n/assets/6220791/3c95314d-2740-40ab-abcc-003a6ab347a0)

**Comment by casaub0n** [comment]
use form state
